CREATE TABLE player (
   player_name TEXT,
   player_link TEXT,
   ht DOUBLE,
   wt DOUBLE,
   _40yd DOUBLE,
   bench DOUBLE,
   broad_jump DOUBLE,
   shuttle DOUBLE,
   _3cone DOUBLE,
   vertical DOUBLE
);

CREATE TABLE pass_tckl (
   player_name TEXT,
   player_link TEXT,
   game TEXT,
   short_r__tckl INT,
   short_r__dfnd INT,
   short_mid__tckl INT,
   short_mid__dfnd INT,
   short_l__tckl INT,
   short_l__dfnd INT,
   deep_r__tckl INT,
   deep_r__dfnd INT,
   deep_mid__tckl INT,
   deep_mid__dfnd INT,
   deep_l__tckl INT,
   deep_l__dfnd INT
);

CREATE TABLE tgt_dir (
   player_name TEXT,
   player_link TEXT,
   game TEXT,
   short_l__tgt INT,
   short_l__ctch INT,
   short_l__yds INT,
   short_l__td INT,
   short_mid__tgt INT,
   short_mid__ctch INT,
   short_mid__yds INT,
   short_mid__td INT,
   short_r__tgt INT,
   short_r__ctch INT,
   short_r__yds INT,
   short_r__td INT,
   deep_l__tgt INT,
   deep_l__ctch INT,
   deep_l__yds INT,
   deep_l__td INT,
   deep_mid__tgt INT,
   deep_mid__ctch INT,
   deep_mid__yds INT,
   deep_mid__td INT,
   deep_r__tgt INT,
   deep_r__ctch INT,
   deep_r__yds INT,
   deep_r__td INT
);
